name: Deploy React App
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code
        uses: actions/checkout@v3
      - name: Install Node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install node modules
        run: npm install
      - name: Build
        uses: npm run build
      - name: Deploy pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          folder: build
          branch: gh-pages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCES_TOKEN }}
